name: Deploy Application

on:
  push:
    branches:
      - staging  # Triggers for staging
      - main     # Triggers for production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to Server
      - name: Deploy to Server
        run: |
          BRANCH=${{ github.ref_name }}
          ENVIRONMENT=$([ "$BRANCH" = "main" ] && echo "production" || echo "staging")

          ssh user@your-server-ip-or-domain << EOF
            cd /home
            git fetch origin $BRANCH
            git reset --hard origin/$BRANCH
            nvm use
            npm install
            pm2 reload ecosystem.config.js --env $ENVIRONMENT
          EOF
